services:
  docdoc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: DocDoc
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./libs:/usr/src/app/libs
    env_file:
      - .env
    command: npm run start:dev
    depends_on:
      - mongo
    dns:
      - 8.8.8.8 # Google DNS
      - 8.8.4.4 # Google DNS

  mongo:
    image: mongo:latest
    container_name: mongo
    attach: false
    restart: always
    ports:
      - '27017:27017'
