services:
  docdoc:
    build: ./
    container_name: DocDoc
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./libs:/usr/src/app/libs
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=secret
      - MONGO_URI=mongodb://mongo:27017
    command: npm run start:dev
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    attach: false
    restart: always
    ports:
      - '27017:27017'
